// Your editor page updates this file directly. You can also edit these words by hand.
const mesiversaryMessage = {
  title: "Haii baby, first of all, I wanted to make a letter only for u, because I love u so much, u have no idea how happy u made my life, and I wanna make ur life happy too 🥺💞",
  introduction: "These five months with u have become some of my favorite days. U bring so much joy and sweetness into my life, and I feel lucky every time I get to call u mine.",
  loveNote: "It honestly feels crazy that it has already been five months since we started this relationship. Five months might not sound like a very long time, but when I think about everything we've gone through together, all the conversations we've had, all the memories we've made, and everything we've learned about each other, it feels like so much more. These months haven't always been perfect. We've had misunderstandings, arguments, moments where we hurt each other, and times when things felt difficult. But even through all of that, I still choose u. I still want us. And I still want to keep learning how to love u better. I love so many little things about u. The way u talk, the things u get excited about, ur silly moments, the things u tell me about your day, and even the little things u probably don't think matter. I love getting to know u more and more, even after five months. I don't expect u to be perfect, and I don't want u to feel like u have to be. I love u as u are, even on the days when u don't feel like urself or when u're struggling to see the good things in u. I hope that, little by little, I can remind u of how much u mean to me. Sometimes the distance really sucks. There are so many moments when I wish I could just be there with u instead of having to put everything I feel into messages. I wish I could hug u when u're having a bad day, sit next to u, laugh with u, and just be there without a screen between us. But even with all these kilometers between us, u've become such an important part of my life. And I really hope this isn't just five months. I hope that one day we'll look back at this time and realize that this was only the beginning. I want to make more memories with u, see u in person, experience things together, and finally have all those moments we've talked about instead of only imagining them. I love u so much. And I hope we get to celebrate many, many more together. -Always urs, mangel :3"




if (typeof module !== "undefined" && module.exports) module.exports = mesiversaryMessage;
if (typeof window !== "undefined") window.MESIVERSARY_MESSAGE = mesiversaryMessage;
